apiVersion: v2
appVersion: 22.2.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.13.*
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 9.8.*
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.6.*
description: A file sharing server that puts the control and security of your own
  data back into your hands.
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
keywords:
- nextcloud
- storage
- http
- web
- php
maintainers:
- email: skjnldsv@protonmail.com
  name: skjnldsv
- email: christian.ingenhaag@googlemail.com
  name: chrisingenhaag
- email: jeff@billimek.com
  name: billimek
name: nextcloud
sources:
- https://github.com/nextcloud/helm
- https://github.com/nextcloud/docker
version: 2.11.3
