apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gitlab-zoekt.fullname" . }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  {{- with .Values.statefulSetAnnotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gitlab-zoekt.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "gitlab-zoekt.fullname" . }}
  replicas: 1 # See https://gitlab.com/gitlab-org/gitlab-build-images/-/issues/118
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gitlab-zoekt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab-zoekt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      {{- if .Values.gateway.basicAuth.enabled }}
      initContainers:
        - name: create-htpasswd
          image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
          command: ['sh', '-c', 'printf "$(cat /etc/nginx/basicauth-credentials/gitlab_username):$(openssl passwd -6 $(cat /etc/nginx/basicauth-credentials/gitlab_password))\n" > /etc/nginx/basicauth/.htpasswd']
          volumeMounts:
            - name: basicauth
              mountPath: /etc/nginx/basicauth
            - name: basicauth-credentials
              mountPath: /etc/nginx/basicauth-credentials
      {{- end }}
      containers:
        - name: zoekt-dynamic-indexserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.dynamicIndexserver.image.repository }}:{{ .Values.dynamicIndexserver.image.tag | default "latest" }}
          imagePullPolicy: {{ coalesce .Values.dynamicIndexserver.image.pullPolicy .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.dynamicIndexserver.listen.port }}
            name: indexserver
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.dynamicIndexserver.listen.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.dynamicIndexserver.listen.port }}
          resources:
            {{- toYaml (merge .Values.dynamicIndexserver.resources .Values.resources) | nindent 12 }}
          volumeMounts:
          - name: zoekt-data
            mountPath: /data/repos
          - name: zoekt-index
            mountPath: /data/index
        - name: zoekt-indexer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default "latest" }}
          imagePullPolicy: {{ coalesce .Values.indexer.image.pullPolicy .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.indexer.listen.port }}
            name: indexer
          livenessProbe:
            httpGet:
              path: /indexer/health
              port: {{ .Values.indexer.listen.port }}
          readinessProbe:
            httpGet:
              path: /indexer/health
              port: {{ .Values.indexer.listen.port }}
          resources:
            {{- toYaml (merge .Values.indexer.resources .Values.resources) | nindent 12 }}
          volumeMounts:
          - name: zoekt-index
            mountPath: /data/index
          {{- if .Values.indexer.googleCloudProfiler.enabled }}
          env:
            - name: GOOGLE_CLOUD_PROFILER_ENABLED
              value: "true"
          {{- end }}
        - name: zoekt-webserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag | default "latest" }}
          imagePullPolicy: {{ coalesce .Values.webserver.image.pullPolicy .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webserver.listen.port }}
              name: webserver
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.webserver.listen.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.webserver.listen.port }}
          resources:
            {{- toYaml (merge .Values.webserver.resources .Values.resources) | nindent 12 }}
          volumeMounts:
          - name: zoekt-index
            mountPath: /data/index
          {{- if .Values.webserver.googleCloudProfiler.enabled }}
          env:
            - name: GOOGLE_CLOUD_PROFILER_ENABLED
              value: "true"
          {{- end }}
        - name: zoekt-gateway
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
          imagePullPolicy: {{ coalesce .Values.gateway.image.pullPolicy .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gateway.listen.port }}
              name: gateway
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.gateway.listen.port }}
              {{- if .Values.gateway.tls.certificate.enabled }}
              scheme: HTTPS
              {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.gateway.listen.port }}
              {{- if .Values.gateway.tls.certificate.enabled }}
              scheme: HTTPS
              {{- end }}
          resources:
            {{- toYaml (merge .Values.gateway.resources .Values.resources) | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            {{- if .Values.gateway.tls.certificate.enabled }}
            - name: gateway-cert
              mountPath: /etc/ssl/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: gateway-cert
              mountPath: /etc/ssl/tls.key
              subPath: tls.key
              readOnly: true
            {{- end }}
            {{- if .Values.gateway.basicAuth.enabled }}
            - name: basicauth
              mountPath: /etc/nginx/basicauth
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "gitlab-zoekt.configMapName" . }}
            items:
              - key: nginx.conf
                path: nginx.conf
        {{- if .Values.gateway.tls.certificate.enabled }}
        - name: gateway-cert
          secret:
            secretName: {{ .Values.gateway.tls.certificate.secretName }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- end }}
        {{- if .Values.gateway.basicAuth.enabled }}
        - name: basicauth
          emptyDir:
            sizeLimit: 1Mi
        - name: basicauth-credentials
          secret:
            secretName: {{ include "gitlab-zoekt.basicAuth.secretName" . }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: zoekt-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.bareRepoStorageClassName }}
      resources:
        requests:
          storage: {{ .Values.bareRepoStorage }}
  - metadata:
      name: zoekt-index
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName:  {{ .Values.indexStorageClassName }}
      resources:
        requests:
          storage: {{ .Values.indexStorage }}
