apiVersion: v2
appVersion: 2.2.0
description: A Helm chart for InfluxDB v2
home: https://www.influxdata.com/products/influxdb/
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
name: influxdb2
type: application
version: 2.1.0
