{{- if .Values.enabled -}}
{{- if eq .Values.global.ingress.provider "traefik" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-gitlab-shell
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ template "fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ include "gitlab.shell.port" . | int }}
      {{- if .Values.global.shell.tcp.proxyProtocol }}
      proxyProtocol:
        version: 2
      {{- end }}
{{- end -}}
{{- end -}}
